apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 7.14.1
  http:
    service:
      spec:
        type: ClusterIP
    tls: 
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - config:
        node.store.allow_mmap: false
        node.master: true
        node.data: false
      name: master
      count: 1
      podTemplate:
        metadata: {}
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms1g -Xmx1g'
              name: elasticsearch
              resources:
                limits:
                  cpu: 1000m
                  memory: 2000Mi
                requests:
                  cpu: 300m
                  memory: 2000Mi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gpa2
    - config: 
          node.store.allow_mmap: false
          node.master: false
          node.data: true
          node.attr.data: hot
      name: data-hot
      count: 1
      podTemplate:
        metadata: {}
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms1g -Xmx1g'
              name: elasticsearch
              resources:
                limits:
                  cpu: 1000m
                  memory: 2000Mi
                requests:
                  cpu: 200m
                  memory: 200Mi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard
    - config: 
          node.store.allow_mmap: false
          node.master: false
          node.data: true
          node.attr.data: warm
      name: data-warm
      count: 1
      podTemplate:
        metadata: {}
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms1g -Xmx1g'
              name: elasticsearch
              resources:
                limits:
                  cpu: 1000m
                  memory: 2000Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          nodeSelector:
            cloud.google.com/gke-nodepool: warm-group
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard
    - config: 
          node.store.allow_mmap: false
          node.master: false
          node.data: true
          node.attr.data: cold
      name: data-cold
      count: 1
      podTemplate:
        metadata: {}
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms1g -Xmx1g'
              name: elasticsearch
              resources:
                limits:
                  cpu: 1000m
                  memory: 2000Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          nodeSelector:
            cloud.google.com/gke-nodepool: cold-group
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: elastic
    annotations:
      kubernetes.io/ingress.class: kong
spec:
  tls:
    - hosts:
       - example.com
      secretName: example-secret
  rules:
    - host: example.com
      http:
        paths:
         - backend:
            serviceName: elastic-es-http
            servicePort: 9200
